<?php

use Core\App;
use Core\Database;
use Core\Installer;
use Core\Validator;

/**
 * Switch the application to a different database (admin only).
 *
 * The credentials are validated with a temporary PDO connection and the
 * target schema must already exist. On success the config is written to
 * storage/config.local.php (never to the settings table) and the current
 * session is destroyed so the next request starts cleanly on the new DB.
 */

// ── Read POST data ──────────────────────────────────────────────────

$values = [
    "db_host" => trim($_POST["db_host"] ?? ""),
    "db_port" => trim($_POST["db_port"] ?? ""),
    "db_name" => trim($_POST["db_name"] ?? ""),
    "db_user" => trim($_POST["db_user"] ?? ""),
];

$password = $_POST["db_password"] ?? "";

// ── Validate fields ─────────────────────────────────────────────────

$errors = [];

if (!Validator::required($values["db_host"])) {
    $errors["db_host"] = "Database host is required.";
}

if ($values["db_port"] === "" || !ctype_digit($values["db_port"])) {
    $errors["db_port"] = "Database port must be a number.";
}

if (!preg_match('/^[A-Za-z0-9_]+$/', $values["db_name"])) {
    $errors["db_name"] =
        "Database name is required (letters, digits and underscores only).";
}

if (!Validator::required($values["db_user"])) {
    $errors["db_user"] = "Database user is required.";
}

// ── Verify connection + schema with a temporary PDO instance ───────

if (empty($errors)) {
    $candidate = [
        "database" => [
            "host" => $values["db_host"],
            "port" => (int) $values["db_port"],
            "dbname" => $values["db_name"],
            "charset" => "utf8mb4",
        ],
        "username" => $values["db_user"],
        "password" => $password,
    ];

    try {
        $pdo = Installer::connect($candidate, true);

        if (!Installer::schemaExists($pdo, $values["db_name"])) {
            $errors["db_schema"] =
                "The target database is reachable but is missing the application schema " .
                "(users, settings, plants, tags). Initialize it first.";
        }
    } catch (PDOException $e) {
        $errors["db_connection"] =
            "Could not connect to the target database: " . $e->getMessage();
    }
}

// ── Save the local config override ──────────────────────────────────

if (empty($errors)) {
    $export =
        "<?php\n\n// Generated by the admin settings page (/settings).\nreturn " .
        var_export($candidate, true) .
        ";\n";

    if (file_put_contents(Installer::localConfigPath(), $export) === false) {
        $errors["db_save"] =
            "Connection works, but the config file could not be written to storage/config.local.php.";
    }
}

// ── On error, re-render the settings page (still on the current DB) ─

if (!empty($errors)) {
    $db = App::resolve(Database::class);

    $settings = [];
    foreach ($db->query("SELECT * FROM settings")->get() as $row) {
        $settings[$row["key"]] = $row["value"];
    }

    return view("settings/edit.view.php", [
        "heading" => "Settings",
        "settings" => $settings,
        "errors" => $errors,
        "dbValues" => $values,
    ]);
}

// ── Success — start the next request cleanly on the new database ────

destroy_session();

redirect("/");
