<table align="center" border="1">
    <tr>
        <td>
            <p align="center"><b>Maps</b></p>
            <a target="_blank" href="https://leafletjs.com/reference.html">Open Street Maps API Reference Guide</a><br>
            <a target="_blank" href="https://github.com/Leaflet/Leaflet.markercluster">Beautiful Animated Marker Clustering functionality for Leaflet</a><br>
            <a target="_blank" href="https://openrouteservice.org/">Highly customizable, performant routing service written in Java</a><br>
        </td>
        <td>
            <p align="center"><b>Geo referencing services</b></p>
            <a target="_blank" href="https://geoapi.pt/">Data on official administrative regions, georeferencing, censuses and postal codes</a><br>
            <a target="_blank" href="http://geodivagar.appspot.com/">Geo referencing services using JSON</a><br>
        </td>    
    </tr>

    <tr>
        <td>
            <p align="center"><b>Image Manipulation Using PHP</b></p>
            <a target="_blank" href="http://www.php.net/manual/en/refs.utilspec.image.php">Image Manipulation Using PHP</a><br>
        </td>
        <td>
            <p align="center"><b>Video/Audio Players</b></p>
            <a target="_blank" href="http://www.longtailvideo.com/players/">JW Player</a><br>
        </td>    
    </tr>

    <tr>
        <td>
            <p align="center"><b>Chart Libraries</b></p>
            <a target="_blank" href="http://jpgraph.net/">JpGraph - Object-Oriented Graph creating library for PHP</a><br>
            <a target="_blank" href="http://www.phplot.com/">PHPlot - Graph library for dynamic scientific, business, and stock-market charts</a><br>
            <!--<a target="_blank" href="http://www.maani.us/charts/">XML/SWF - A simple, yet powerful tool to create attractive charts and graphs from XML data</a><br>-->
            <a target="_blank" href="http://naku.dohcrew.com/libchart/">Libchart - A free chart creation PHP library, that is easy to use</a><br>
        </td>
        <td>
            <p align="center"><b>ffmpeg Library</b></p>
            <a target="_blank" href="http://ffmpeg.org/">ffmpeg</a><br>
            &nbsp;<br>
            &nbsp;<br>
            &nbsp;<br>
        </td>
    </tr>
</table>
