<p>Data Access Demo Web Services</p>
<a target="_blank" href="https://www.dataaccess.com/webservicesserver/TextCasing.wso">Text Casing</a><br>
<a target="_blank" href="https://www.dataaccess.com/webservicesserver/NumberConversion.wso">Number Conversion</a><br>

<p>G Computer Network Demo Web Services</p>
<a target="_blank" href="http://www.gcomputer.net/webservices/knowledge.asmx">The Knowledge Leak</a><br>
<a target="_blank" href="http://www.gcomputer.net/webservices/dilbert.asmx">Daily Dilbert</a><br>

<p>Free Web Services</p>
<a target="_blank" href="http://free-web-services.com/">Free Web Services</a><br>

