<p class='mainPageEntry'>Authentication</p>

<span class='mainPageEntry menuItemL1'><a target="_blank" href="http://httpd.apache.org/docs/2.0/howto/auth.html">Authentication, Authorization and Access Control - Apache 2.0</a></span><br>
<span class='mainPageEntry menuItemL1'><a target="_blank" href="http://www.php.net/manual/en/features.http-auth.php">HTTP authentication with PHP</a></span><br>
<span class='mainPageEntry menuItemL1'><a target="_blank" href="http://httpd.apache.org/docs/2.0/mod/mod_auth_ldap.html">Apache Module mod_auth_ldap</a></span><br>

<p class='mainPageEntry'>LDAP - OpenLDAP</p>
<span class='mainPageEntry menuItemL1'><a target="_blank" href="http://directory.apache.org/">The Apache Directory Project</a></span><br>

<p class='mainPageEntry'>Scripts</p>

<p class='mainPageEntry menuItemL1'>Certificates</p>
<span class='mainPageEntry menuItemL2'><a target="_blank" href="showScript.php?file=genCertificate.bat">genCertificate.bat</a></span><br>
<span class='mainPageEntry menuItemL2'><a target="_blank" href="showScript.php?file=genCertificate.sh">genCertificate.sh</a></span><br>

<p class='mainPageEntry menuItemL1'>Account Management</p>
<span class='mainPageEntry menuItemL2'><a target="_blank" href="showScript.php?file=createUsers.bat">createUsers.bat</a></span><br>