<?php

use Core\Installer;
use Core\Validator;

// Already fully installed — nothing to do here.
if (Installer::state() === "ready") {
    redirect("/");
}

// ── Read POST data ──────────────────────────────────────────────────

$values = [
    "db_host" => trim($_POST["db_host"] ?? ""),
    "db_port" => trim($_POST["db_port"] ?? ""),
    "db_name" => trim($_POST["db_name"] ?? ""),
    "db_user" => trim($_POST["db_user"] ?? ""),
];

$password = $_POST["db_password"] ?? "";

// ── Validate ────────────────────────────────────────────────────────

$errors = [];

if (!Validator::required($values["db_host"])) {
    $errors["db_host"] = "Database host is required.";
}

if ($values["db_port"] === "" || !ctype_digit($values["db_port"])) {
    $errors["db_port"] = "Database port must be a number.";
}

if (!preg_match('/^[A-Za-z0-9_]+$/', $values["db_name"])) {
    $errors["db_name"] =
        "Database name is required (letters, digits and underscores only).";
}

if (!Validator::required($values["db_user"])) {
    $errors["db_user"] = "Database user is required.";
}

// ── Verify the connection with a temporary PDO instance ────────────

if (empty($errors)) {
    $candidate = [
        "database" => [
            "host" => $values["db_host"],
            "port" => (int) $values["db_port"],
            "dbname" => $values["db_name"],
            "charset" => "utf8mb4",
        ],
        "username" => $values["db_user"],
        "password" => $password,
    ];

    try {
        Installer::connect($candidate, true);
    } catch (PDOException) {
        // The database may not exist yet — a server-level connection is
        // enough, since /install/schema creates the database itself.
        try {
            Installer::connect($candidate, false);
        } catch (PDOException $e) {
            $errors["connection"] =
                "Could not connect to the database server: " . $e->getMessage();
        }
    }
}

if (!empty($errors)) {
    return view("install/database.view.php", [
        "errors" => $errors,
        "values" => $values,
    ]);
}

// ── Save the config override locally ────────────────────────────────

$export =
    "<?php\n\n// Generated by the first-run installer (/install/database).\nreturn " .
    var_export($candidate, true) .
    ";\n";

if (file_put_contents(Installer::localConfigPath(), $export) === false) {
    return view("install/database.view.php", [
        "errors" => [
            "save" => "Connection works, but the config file could not be written to storage/config.local.php.",
        ],
        "values" => $values,
    ]);
}

redirect("/install/schema");
