<p><b>Notes:</b></p>
<p><span class='mainPageEntry'>
        <a href="https://leafletjs.com/reference.html" 
           target="_blank" 
           title="Open Street Maps API">Open Street Maps API Reference Guide</a></span></p>

<p><span class='mainPageEntry'>
        <a href="https://github.com/Leaflet/Leaflet.markercluster" 
           target="_blank" 
           title="Leaflet Marker Cluster">Beautiful Animated Marker Clustering functionality for Leaflet</a></span></p>

<p><span class='mainPageEntry'>
        <a href="https://openrouteservice.org/" 
           target="_blank" 
           title="Open Route Service">Highly customizable, performant routing service written in Java</a></span></p>

<p><span class='mainPageEntry'>
        <a href="https://geoapi.pt/docs/"
           target="_blank"
           title="GEO API">GEO API - Dados de Portugal sobre Regiões Administrativas, Georreferenciação, Censos e Códigos Postais</a></span></p>
