services:
  web:
    build: ./web
    container_name: smi-web
    ports:
      - "8080:80"
    environment:
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.1
    container_name: smi-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    container_name: smi-pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  db_data:
